# -*- coding: utf-8 -*-
"""Node2Vec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_k1PhK0kPo0Q5b7e-XjZHd_MboP6kOO
"""

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Copy of Epinions/Data-final/trust_new.csv")
data = data[["from","to","value"]]
#data["value"] = abs(data["value"])

import networkx as nx
G = nx.Graph()

G = nx.from_pandas_edgelist(data, 'to', 'from')

!pip install node2vec

from node2vec import Node2Vec

node2vec = Node2Vec(G, dimensions=64, walk_length=100, num_walks=75)

model = node2vec.fit(window=5, min_count=1, batch_words=1000)  # Any keywords acceptable by gensim.Word2Vec can be passed, `diemnsions` and `workers` are automatically passed (from the Node2Vec constructor)

import numpy as np
np.savetxt('/content/drive/MyDrive/Copy of Epinions/Data-final/unsigned_user_embeddings_final100.txt', model.wv.vectors)



import numpy as np
np.loadtxt('/content/drive/MyDrive/Copy of Epinions/Ciao/unsigned_user_embeddings.txt').shape

import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Copy of Epinions/Data-final/ratings_data.csv")

data = data[["userId","productId"]]
data.groupby("productId").count().mean()

import networkx as nx
G = nx.Graph()

G = nx.from_pandas_edgelist(data, 'productId', 'userId')

!pip install node2vec

from node2vec import Node2Vec

node2vec = Node2Vec(G, dimensions=64, walk_length=5, num_walks=100)
model = node2vec.fit(window=5, min_count=1, batch_words=1000)  # Any keywords acceptable by gensim.Word2Vec can be passed, `diemnsions` and `workers` are automatically passed (from the Node2Vec constructor)
import numpy as np
np.savetxt('/content/drive/MyDrive/Copy of Epinions/Data-final/unsigned_item_embeddings_50.txt', model.wv.vectors)

